#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  touche,         sensorTouch)
#pragma config(Motor,  port1,            ,             tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           right1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           right2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          backRight,     tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#define lift -motor[left1] = motor[right1] = -motor[left2] = motor[right2]

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
/*****************************************************************************************
Hi, I'm Elias Griffith, the main programmer for 2616K, Knights of Stars. I have a very
extensive background in computer science and programming, starting with Python, HTML, and Javascript
and recently started approaching assembly language and C#. My proper introduction is here
because where else could be more fitting for a programmer to introduce themselves than their
own program?!
Anyways, enough talk about how I bodge my programs together last minute, and am writing this
at 1:26 AM on the day of my first competition of the year, let's get to know you...

Seriously, I swear this engineering notebook is good, we've worked day and night since April
22.
******************************************************************************************/
/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
		bLCDBacklight = true;
		if(vexRT[Btn6U]){
			if(motor[left1] == 0) {
				motor[left1] = 63;
				motor[left2] = 63;
				motor[right1] = -63;
				motor[right2] = -63;
			}
		}
		while(vexRT[Btn6U]){
		}
		motor[left1] = 0;
		motor[right1] = 0;
		motor[left2] = 0;
		motor[right2] = 0;
		while (vexRT[Btn6D]) {
			if(motor[left1] == 0){
				motor[left1] = -127;
				motor[right1] = 127;
				motor[left2] = -127;
				motor[right2] = 127;
			}
		}
		motor[left1] = 0;
		motor[right1] = 0;
		motor[left2] = 0;
		motor[right2] = 0;
		if(!vexRT[Btn6D] || !vexRT[Btn6U]){

		}
		if(vexRT[Btn8D]){
			motor[frontLeft] = -127;
			motor[frontRight] = 127;
			motor[backLeft] = -127;
			motor[backRight] = 127;

			} else if (vexRT[Btn8U]) {
			motor[frontLeft] = 127;
			motor[frontRight] = -127;
			motor[backLeft] = 127;
			motor[backRight] = -127;
		} else if (vexRT[Ch1] < -32){
			motor[frontLeft] =  127;
			motor[frontRight] = -	127;
			motor[backLeft] = -127;
			motor[backRight] = 127;
		} else if (vexRT[Btn8R]) {
			motor[frontLeft] = -127;
			motor[frontRight] = 127;
			motor[backLeft] = 127;
			motor[backRight] = -127;
		} else if(-32 > vexRT[Ch4] || vexRT[Ch4] > 32) {
			motor[frontLeft] = vexRT[Ch4];
			motor[frontRight] = vexRT[Ch4];
			motor[backLeft] = vexRT[Ch4];
			motor[backRight] = vexRT[Ch4];
		} else {
			motor[frontLeft] = 0;
			motor[frontRight] = 0;
			motor[backLeft] = 0;
			motor[backRight] = 0;
		}
	}
}
